-- MySQL Script generated by MySQL Workbench
-- 09/25/19 20:24:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `idprod` INT NOT NULL AUTO_INCREMENT,
  `nomprod` VARCHAR(500) NULL,
  `prix` INT NULL,
  `qtestock` INT NULL,
  `description` VARCHAR(500) NULL,
  `categorie` VARCHAR(50) NULL,
  `couleur` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idprod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `idutilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(500) NULL,
  `age` INT NULL,
  `photo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pwd` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idutilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `idcmd` INT NOT NULL AUTO_INCREMENT,
  `idprod` INT NULL,
  `idutilisateur` INT NULL,
  `datecmd` DATE NULL,
  `qtecmd` INT NULL,
  PRIMARY KEY (`idcmd`),
  INDEX `idprod_idx` (`idprod` ASC),
  INDEX `idutilisateur_idx` (`idutilisateur` ASC),
  CONSTRAINT `idprod`
    FOREIGN KEY (`idprod`)
    REFERENCES `mydb`.`produit` (`idprod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idutilisateur`
    FOREIGN KEY (`idutilisateur`)
    REFERENCES `mydb`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
